use crate::services::agent_cli::{
    contracts::AgentAssetSourceSpec,
    environment::preview::{
        AgentArgvPolicy, AgentArgvValueKind as V, AgentArgvValueRule, AgentPreviewFormat,
        AgentPreviewPathSegment::{AnyIndex as I, AnyKey as A, Key as K},
        AgentPreviewPolicy, AgentPreviewRule as R, AgentPreviewScalarKind as S,
        AgentSourcePreviewPolicy,
    },
};

const ARGV: AgentArgvPolicy = AgentArgvPolicy {
    command_field: "command",
    launchers: &[
        "node",
        "node.exe",
        "python",
        "python3",
        "python.exe",
        "python3.exe",
        "npx",
        "npx.cmd",
        "uvx",
        "uvx.exe",
    ],
    boolean_flags: &[
        "-y",
        "--yes",
        "--stdio",
        "--verbose",
        "--quiet",
        "--debug",
        "--help",
        "--version",
    ],
    value_flags: &[
        AgentArgvValueRule {
            flag: "--port",
            kind: V::Integer,
        },
        AgentArgvValueRule {
            flag: "--timeout",
            kind: V::Integer,
        },
        AgentArgvValueRule {
            flag: "--host",
            kind: V::Host,
        },
        AgentArgvValueRule {
            flag: "--cwd",
            kind: V::Path,
        },
        AgentArgvValueRule {
            flag: "--url",
            kind: V::Url,
        },
        AgentArgvValueRule {
            flag: "--transport",
            kind: V::Enum(&["stdio", "http", "sse"]),
        },
        AgentArgvValueRule {
            flag: "--log-level",
            kind: V::Enum(&["trace", "debug", "info", "warn", "error"]),
        },
    ],
    credential_flags: &[
        "--api-key",
        "--apikey",
        "--apiKey",
        "--key",
        "--token",
        "--access-token",
        "--bearer-token",
        "--password",
        "--cookie",
        "--authorization",
        "--header",
        "-H",
    ],
};

static SETTINGS: AgentPreviewPolicy = AgentPreviewPolicy {
    schema_id: "claude.settings",
    schema_version: 1,
    policy_id: "claude.settings.preview",
    policy_version: 1,
    format: AgentPreviewFormat::Json,
    rules: &[
        R::url(&[K("env"), K("ANTHROPIC_BASE_URL")], &[]),
        R::scalar(&[K("env"), K("ANTHROPIC_MODEL")], S::Identifier),
        R::scalar(
            &[K("env"), K("ANTHROPIC_DEFAULT_OPUS_MODEL")],
            S::Identifier,
        ),
        R::scalar(
            &[K("env"), K("ANTHROPIC_DEFAULT_SONNET_MODEL")],
            S::Identifier,
        ),
        R::scalar(
            &[K("env"), K("ANTHROPIC_DEFAULT_HAIKU_MODEL")],
            S::Identifier,
        ),
        R::scalar(&[K("effortLevel")], S::Identifier),
        R::scalar(&[K("permissions"), K("defaultMode")], S::Identifier),
        R::scalar(&[K("theme")], S::Identifier),
        R::scalar(&[K("language")], S::Identifier),
        R::scalar(&[K("alwaysThinkingEnabled")], S::Boolean),
        R::scalar(&[K("managedMcpServers"), A, K("command")], S::Executable),
        R::argv(&[K("managedMcpServers"), A, K("args")], &ARGV),
        R::scalar(&[K("managedMcpServers"), A, K("cwd")], S::Path),
        R::url(&[K("managedMcpServers"), A, K("url")], &["transport"]),
        R::scalar(&[K("managedMcpServers"), A, K("enabled")], S::Boolean),
        R::scalar(&[K("managedMcpServers"), A, K("disabled")], S::Boolean),
        R::scalar(
            &[K("managedMcpServers"), A, K("type")],
            S::Enum(&["stdio", "http", "sse", "websocket"]),
        ),
        R::scalar(
            &[K("managedMcpServers"), A, K("transport")],
            S::Enum(&["stdio", "http", "sse", "websocket"]),
        ),
        R::scalar(&[K("managedMcpServers"), A, K("timeout")], S::Number),
        R::scalar(
            &[K("managedMcpServers"), A, K("startup_timeout_sec")],
            S::Number,
        ),
        R::hide_values(&[K("managedMcpServers"), A, K("env")]),
        R::hide_values(&[K("managedMcpServers"), A, K("headers")]),
        R::hide_values(&[K("managedMcpServers"), A, K("http_headers")]),
        R::hide_values(&[K("managedMcpServers"), A, K("env_http_headers")]),
        R::hide_values(&[K("managedMcpServers"), A, K("auth")]),
        R::hide_values(&[K("managedMcpServers"), A, K("oauth")]),
        R::hide(&[K("managedMcpServers"), A, K("api_key")]),
        R::hide(&[K("managedMcpServers"), A, K("apiKey")]),
        R::hide(&[K("managedMcpServers"), A, K("token")]),
        R::hide(&[K("managedMcpServers"), A, K("bearer_token")]),
        R::hide(&[K("managedMcpServers"), A, K("password")]),
        R::hide(&[K("managedMcpServers"), A, K("cookie")]),
        R::scalar(&[K("model")], S::Identifier),
        R::scalar(&[K("enabledPlugins"), A], S::Boolean),
        R::scalar(&[K("disableAllHooks")], S::Boolean),
        R::scalar(&[K("enableAllProjectMcpServers")], S::Boolean),
        R::scalar(&[K("enabledMcpjsonServers"), I], S::Identifier),
        R::scalar(&[K("disabledMcpjsonServers"), I], S::Identifier),
        R::scalar(&[K("statusLine"), K("type")], S::Enum(&["command"])),
        R::scalar(&[K("statusLine"), K("command")], S::Executable),
        R::scalar(&[K("statusLine"), K("padding")], S::Number),
        R::hide(&[K("apiKeyHelper")]),
        R::scalar(
            &[K("hooks"), A, I, K("hooks"), I, K("type")],
            S::Enum(&["command", "prompt", "http"]),
        ),
        R::scalar(
            &[K("hooks"), A, I, K("hooks"), I, K("command")],
            S::Executable,
        ),
        R::url(&[K("hooks"), A, I, K("hooks"), I, K("url")], &[]),
        R::scalar(&[K("hooks"), A, I, K("hooks"), I, K("timeout")], S::Number),
        R::hide_values(&[K("hooks"), A, I, K("hooks"), I, K("headers")]),
        R::hide_values(&[K("hooks"), A, I, K("hooks"), I, K("env")]),
        R::hide(&[K("hooks"), A, I, K("hooks"), I, K("prompt")]),
    ],
};

static ACCOUNT: AgentPreviewPolicy = AgentPreviewPolicy {
    schema_id: "claude.account",
    schema_version: 1,
    policy_id: "claude.account.preview",
    policy_version: 1,
    format: AgentPreviewFormat::Json,
    rules: &[
        R::scalar(&[K("mcpServers"), A, K("command")], S::Executable),
        R::argv(&[K("mcpServers"), A, K("args")], &ARGV),
        R::scalar(&[K("mcpServers"), A, K("cwd")], S::Path),
        R::url(&[K("mcpServers"), A, K("url")], &["transport"]),
        R::scalar(&[K("mcpServers"), A, K("enabled")], S::Boolean),
        R::scalar(&[K("mcpServers"), A, K("disabled")], S::Boolean),
        R::scalar(
            &[K("mcpServers"), A, K("type")],
            S::Enum(&["stdio", "http", "sse", "websocket"]),
        ),
        R::scalar(
            &[K("mcpServers"), A, K("transport")],
            S::Enum(&["stdio", "http", "sse", "websocket"]),
        ),
        R::scalar(&[K("mcpServers"), A, K("timeout")], S::Number),
        R::scalar(&[K("mcpServers"), A, K("startup_timeout_sec")], S::Number),
        R::hide_values(&[K("mcpServers"), A, K("env")]),
        R::hide_values(&[K("mcpServers"), A, K("headers")]),
        R::hide_values(&[K("mcpServers"), A, K("http_headers")]),
        R::hide_values(&[K("mcpServers"), A, K("env_http_headers")]),
        R::hide_values(&[K("mcpServers"), A, K("auth")]),
        R::hide_values(&[K("mcpServers"), A, K("oauth")]),
        R::hide(&[K("mcpServers"), A, K("api_key")]),
        R::hide(&[K("mcpServers"), A, K("apiKey")]),
        R::hide(&[K("mcpServers"), A, K("token")]),
        R::hide(&[K("mcpServers"), A, K("bearer_token")]),
        R::hide(&[K("mcpServers"), A, K("password")]),
        R::hide(&[K("mcpServers"), A, K("cookie")]),
        R::scalar(
            &[K("projects"), A, K("mcpServers"), A, K("command")],
            S::Executable,
        ),
        R::argv(&[K("projects"), A, K("mcpServers"), A, K("args")], &ARGV),
        R::scalar(&[K("projects"), A, K("mcpServers"), A, K("cwd")], S::Path),
        R::url(
            &[K("projects"), A, K("mcpServers"), A, K("url")],
            &["transport"],
        ),
        R::scalar(
            &[K("projects"), A, K("mcpServers"), A, K("enabled")],
            S::Boolean,
        ),
        R::scalar(
            &[K("projects"), A, K("mcpServers"), A, K("disabled")],
            S::Boolean,
        ),
        R::scalar(
            &[K("projects"), A, K("mcpServers"), A, K("type")],
            S::Enum(&["stdio", "http", "sse", "websocket"]),
        ),
        R::scalar(
            &[K("projects"), A, K("mcpServers"), A, K("transport")],
            S::Enum(&["stdio", "http", "sse", "websocket"]),
        ),
        R::scalar(
            &[K("projects"), A, K("mcpServers"), A, K("timeout")],
            S::Number,
        ),
        R::scalar(
            &[
                K("projects"),
                A,
                K("mcpServers"),
                A,
                K("startup_timeout_sec"),
            ],
            S::Number,
        ),
        R::hide_values(&[K("projects"), A, K("mcpServers"), A, K("env")]),
        R::hide_values(&[K("projects"), A, K("mcpServers"), A, K("headers")]),
        R::hide_values(&[K("projects"), A, K("mcpServers"), A, K("http_headers")]),
        R::hide_values(&[K("projects"), A, K("mcpServers"), A, K("env_http_headers")]),
        R::hide_values(&[K("projects"), A, K("mcpServers"), A, K("auth")]),
        R::hide_values(&[K("projects"), A, K("mcpServers"), A, K("oauth")]),
        R::hide(&[K("projects"), A, K("mcpServers"), A, K("api_key")]),
        R::hide(&[K("projects"), A, K("mcpServers"), A, K("apiKey")]),
        R::hide(&[K("projects"), A, K("mcpServers"), A, K("token")]),
        R::hide(&[K("projects"), A, K("mcpServers"), A, K("bearer_token")]),
        R::hide(&[K("projects"), A, K("mcpServers"), A, K("password")]),
        R::hide(&[K("projects"), A, K("mcpServers"), A, K("cookie")]),
        R::hide_values(&[K("oauthAccount")]),
        R::hide_values(&[K("auth")]),
        R::hide_values(&[K("env")]),
    ],
};

static MCP: AgentPreviewPolicy = AgentPreviewPolicy {
    schema_id: "claude.mcp",
    schema_version: 1,
    policy_id: "claude.mcp.preview",
    policy_version: 1,
    format: AgentPreviewFormat::Json,
    rules: &[
        R::scalar(&[K("mcpServers"), A, K("command")], S::Executable),
        R::argv(&[K("mcpServers"), A, K("args")], &ARGV),
        R::scalar(&[K("mcpServers"), A, K("cwd")], S::Path),
        R::url(&[K("mcpServers"), A, K("url")], &["transport"]),
        R::scalar(&[K("mcpServers"), A, K("enabled")], S::Boolean),
        R::scalar(&[K("mcpServers"), A, K("disabled")], S::Boolean),
        R::scalar(
            &[K("mcpServers"), A, K("type")],
            S::Enum(&["stdio", "http", "sse", "websocket"]),
        ),
        R::scalar(
            &[K("mcpServers"), A, K("transport")],
            S::Enum(&["stdio", "http", "sse", "websocket"]),
        ),
        R::scalar(&[K("mcpServers"), A, K("timeout")], S::Number),
        R::scalar(&[K("mcpServers"), A, K("startup_timeout_sec")], S::Number),
        R::hide_values(&[K("mcpServers"), A, K("env")]),
        R::hide_values(&[K("mcpServers"), A, K("headers")]),
        R::hide_values(&[K("mcpServers"), A, K("http_headers")]),
        R::hide_values(&[K("mcpServers"), A, K("env_http_headers")]),
        R::hide_values(&[K("mcpServers"), A, K("auth")]),
        R::hide_values(&[K("mcpServers"), A, K("oauth")]),
        R::hide(&[K("mcpServers"), A, K("api_key")]),
        R::hide(&[K("mcpServers"), A, K("apiKey")]),
        R::hide(&[K("mcpServers"), A, K("token")]),
        R::hide(&[K("mcpServers"), A, K("bearer_token")]),
        R::hide(&[K("mcpServers"), A, K("password")]),
        R::hide(&[K("mcpServers"), A, K("cookie")]),
    ],
};

pub(crate) fn source_preview(source: &AgentAssetSourceSpec) -> AgentSourcePreviewPolicy {
    match source.native_source_key.as_str() {
        "settings"
        | "workspace-settings"
        | "workspace-local-settings"
        | "workspace-root-local-settings"
        | "managed-settings" => AgentSourcePreviewPolicy::structured(&SETTINGS),
        "account" => AgentSourcePreviewPolicy::structured(&ACCOUNT),
        "workspace-mcp" | "managed-mcp" => AgentSourcePreviewPolicy::structured(&MCP),
        _ => AgentSourcePreviewPolicy::metadata_only(),
    }
}
