import {
  DEFAULT_LIVENESS_FIXED_PROMPT,
  DEFAULT_LIVENESS_INTERVAL,
  DEFAULT_LIVENESS_MODEL,
  DEFAULT_LIVENESS_NUMBER_MAX,
  DEFAULT_LIVENESS_NUMBER_MIN,
  DEFAULT_LIVENESS_RANDOM_MIN_INTERVAL,
  DEFAULT_LIVENESS_TIMEOUT,
  defaultLivenessPlaceholderPools,
  defaultLivenessPromptLibrary,
} from "../utils/liveness-defaults";
import type { AppSettings } from "./provider-types";

export const defaultSettings = (): AppSettings => ({
  onboardingCompleted: false,
  refreshInterval: 300,
  launchAtLogin: false,
  launchAtLoginMinimized: false,
  proxyMode: "system",
  proxyUrl: "",
  themeMode: "system",
  autoRefreshEnabled: true,
  autoCheckInEnabled: true,
  checkInTime: "00:00",
  notificationEnabled: true,
  notificationChannels: [
    {
      id: "system",
      name: "系统通知",
      kind: "system",
      url: "",
      secret: "",
      enabled: true,
    },
  ],
  glassTransparency: 58,
  livenessCliKind: "codex",
  livenessMethod: "cli",
  livenessHttpProtocol: "openaiChat",
  codexCliPath: "",
  claudeCliPath: "",
  temporaryCliTerminalKind: "auto",
  temporaryCliTerminalCommand: "",
  livenessEnabled: false,
  livenessModel: DEFAULT_LIVENESS_MODEL,
  livenessIntervalMode: "fixed",
  livenessInterval: DEFAULT_LIVENESS_INTERVAL,
  livenessRandomMinInterval: DEFAULT_LIVENESS_RANDOM_MIN_INTERVAL,
  livenessRandomMaxInterval: DEFAULT_LIVENESS_INTERVAL,
  livenessTimeout: DEFAULT_LIVENESS_TIMEOUT,
  livenessPromptMode: "random",
  livenessFixedPrompt: DEFAULT_LIVENESS_FIXED_PROMPT,
  livenessPromptLibrary: defaultLivenessPromptLibrary(),
  livenessPlaceholderPools: defaultLivenessPlaceholderPools(),
  livenessNumberMin: DEFAULT_LIVENESS_NUMBER_MIN,
  livenessNumberMax: DEFAULT_LIVENESS_NUMBER_MAX,
  livenessConsentAcceptedAt: null,
});
