#[path = "provider_domain/auth.rs"]
pub mod auth;
#[path = "provider_domain/automation.rs"]
pub mod automation;
#[path = "provider_domain/capabilities.rs"]
pub mod capabilities;
#[path = "provider_domain/check_in.rs"]
pub mod check_in;
#[path = "provider_domain/liveness.rs"]
pub mod liveness;
